# Fichier inspiré du répertoire actions/setup-node : https://github.com/actions/setup-node

name: "Continuous Integration"

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
      - releases/*
      - features/*
    paths-ignore:
      - '**.md'

jobs:
  quality:
    name: Quality checks
#    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup node 15
          uses: actions/setup-node@v2
          with:
            node-version: 15.x

      - name: Install dependencies
        run: npm install --no-interaction

      - name: Check quality for NPM
        run: npm ci

      - name: Build source code
        run: npm run build

      - name: Run tests
        run: npm test -- --watchAll=false